### Etapa 3 - EDA, Storytelling e visualização

In [ ]:
import pandas as pd
import re

In [ ]:
dataframe_final_candidatos = pd.read_csv('etapa2_dataframe_final_csv')
dataframe_final_candidatos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Data_hora  15000 non-null  object
 1   Id_Tweet   15000 non-null  int64
 2   Tweet      15000 non-null  object
 3   Candidato  15000 non-null  object
dtypes: int64(1), object(3)
memory usage: 468.9+ KB

In [ ]:
dataframe_final_candidatos['Tweet_limpo'] = dataframe_final_candidatos['Tweet']
dataframe_final_candidatos.head()

,Data_hora,Id_Tweet,Tweet,Candidato,Tweet_limpo
0,2022-08-03 01:57:56+00:00,1554647725488185345,@LulaOficial Abram a imagem. 20.000 pessoas ca...,Lula,@LulaOficial Abram a imagem. 20.000 pessoas ca...
1,2022-08-03 01:57:56+00:00,1554647724133437443,@FLina53804079 @LulaOficial @ricardostuckert M...,Lula,@FLina53804079 @LulaOficial @ricardostuckert M...
2,2022-08-03 01:57:55+00:00,1554647722866655233,@DeputadoFederal Jair e Lula: dois pilantras!,Lula,@DeputadoFederal Jair e Lula: dois pilantras!
3,2022-08-03 01:57:55+00:00,1554647720878546948,@RTaokey @LulaOficial BANDIDO #LulaLadrao http...,Lula,@RTaokey @LulaOficial BANDIDO #LulaLadrao http...
4,2022-08-03 01:57:53+00:00,1554647715275067392,@LulaOficial https://t.co/I47E3GfJjQ,Lula,@LulaOficial https://t.co/I47E3GfJjQ

In [ ]:
def limpeza_do_texto(tweet):
  tweet = tweet.lower()
  tweet = re.sub('\n','', tweet)
  tweet = re.sub('@[^\s]+','',tweet)
  tweet = re.sub('\B#\S+','',tweet)
  tweet = re.sub('https?://\S+|www\.\S+','',tweet)
  return tweet

In [ ]:
dataframe_final_candidatos['Tweet_limpo'] = dataframe_final_candidatos['Tweet'].apply(lambda i : limpeza_do_texto(i))
dataframe_final_candidatos.head()

,Data_hora,Id_Tweet,Tweet,Candidato,Tweet_limpo
0,2022-08-03 01:57:56+00:00,1554647725488185345,@LulaOficial Abram a imagem. 20.000 pessoas ca...,Lula,abram a imagem. 20.000 pessoas cabem num quad...
1,2022-08-03 01:57:56+00:00,1554647724133437443,@FLina53804079 @LulaOficial @ricardostuckert M...,Lula,muito mesmo
2,2022-08-03 01:57:55+00:00,1554647722866655233,@DeputadoFederal Jair e Lula: dois pilantras!,Lula,jair e lula: dois pilantras!
3,2022-08-03 01:57:55+00:00,1554647720878546948,@RTaokey @LulaOficial BANDIDO #LulaLadrao http...,Lula,bandido
4,2022-08-03 01:57:53+00:00,1554647715275067392,@LulaOficial https://t.co/I47E3GfJjQ,Lula,

In [ ]:
dataframe_final_candidatos.to_csv('etapa3_dataframe_final_candidatos_pronto_para_sentimento',sep=',',index=False)